name: Globlib regression test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  job1:
    name: Nonconvex QP    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: sqlp/sedumi
          path: sedumi
      
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v0
       
      - name: Nonconvex QP
        uses: matlab-actions/run-command@v0
        with:
          command: addpath(genpath(pwd)); results = runxunittests('dev/tests/globlib/qp'); assertSuccess(results);

      - name: QP report
        uses: dorny/test-reporter@v1.4.3
        if: success() || failure()    
        with:
          name: QP report
          path: qp.xml               
          reporter: java-junit        

  job2:
    name: Nonconvex QCQP    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: sqlp/sedumi
          path: sedumi
      
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v0
       
      - name: Nonconvex QCQP
        uses: matlab-actions/run-command@v0
        with:
          command: addpath(genpath(pwd)); results = runxunittests('dev/tests/globlib/qcqp'); assertSuccess(results);

      - name: QCQP report
        uses: dorny/test-reporter@v1.4.3
        if: success() || failure()    
        with:
          name: QCQP report               
          path: qcqp.xml
          reporter: java-junit       

  job3:
    name: Polynomial    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: sqlp/sedumi
          path: sedumi
      
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v0
       
      - name: Polynomial
        uses: matlab-actions/run-command@v0
        with:
          command: addpath(genpath(pwd)); results = runxunittests('dev/tests/globlib/polynomial'); assertSuccess(results);

      - name: Polynomial report
        uses: dorny/test-reporter@v1.4.3
        if: success() || failure()   
        with:
          name: Polynomial report      
          path: polynomial.xml
          reporter: java-junit       

  job4:
    name: General nonlinear    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: sqlp/sedumi
          path: sedumi
      
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v0
       
      - name: General nonlinear
        uses: matlab-actions/run-command@v0
        with:
          command: addpath(genpath(pwd)); results = runxunittests('dev/tests/globlib/general'); assertSuccess(results);

      - name: General nonlinear report
        uses: dorny/test-reporter@v1.4.3
        if: success() || failure()   
        with:
          name: General nonlinear report
          path: general.xml
          reporter: java-junit       
